# -*- coding: utf-8 -*-
"""lab5&6_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X_7uuPY-YRTGvziwka5tSe3bqv3zq6Wd

##Question 2

###Task 1
"""

from sklearn.datasets import fetch_lfw_people
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

lfw_people = fetch_lfw_people(min_faces_per_person=70, resize=0.4)

lfw_people

X = lfw_people.data
n_features = X.shape[1]

y = lfw_people.target
target_names = lfw_people.target_names
n_classes = target_names.shape[0]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X.shape,y.shape

import matplotlib.pyplot as plt

fig, axes = plt.subplots(4,4,sharex=True,sharey=True,figsize=(8,10))
faceimages = list(X_train)[-16:]
for i in range(16):
    image = faceimages[i].reshape((50,37))
    axes[i%4][i//4].imshow(image, cmap="gray")
plt.show()

"""###Task 2"""

from sklearn.decomposition import PCA
p = 650
model = PCA(p)
model.fit(X_train)
transformed_X_train = model.transform(X_train)
transformed_X_test = model.transform(X_test)

fig, axes = plt.subplots(4,4,sharex=True,sharey=True,figsize=(8,10))
faceimages = list(transformed_X_train)[-16:]
for i in range(16):
    image = faceimages[i].reshape((26, 25))

    axes[i%4][i//4].imshow(image, cmap="gray")
plt.show()

"""###Task 3"""

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=10)
classifier.fit(transformed_X_train, y_train)

"""###Task 4"""

y_pred = classifier.predict(transformed_X_test)
accuracy = np.mean(y_pred == y_test)
print("Accuracy:", accuracy)

"""###Task 5"""

accuracy_values = []
variance = []
n_components_values = [150, 250, 350, 450, 550, 650, 750, 850, 950]

for n_components in n_components_values:
    pca = PCA(n_components=n_components)
    pca.fit(X_train)

    transformed_X_train = pca.transform(X_train)
    transformed_X_test = pca.transform(X_test)

    classifier = KNeighborsClassifier(n_neighbors=10)
    classifier.fit(transformed_X_train, y_train)

    accuracy = classifier.score(transformed_X_test, y_test)
    accuracy_values.append(accuracy)

    variance.append(np.mean(np.cumsum(pca.explained_variance_ratio_)))

for comp, var in zip(n_components_values, variance):
    if(var>=0.95):
        print("Best value for n_components based on explained variance ratio:", comp)
        print("it has variance = ",var)
        break

plt.figure(figsize=(8, 6))
plt.plot(n_components_values, variance, label='variance',color='red')
plt.plot(n_components_values, accuracy_values, label='accuracy', color='blue')
plt.title('Accuracy and variance vs. Number of Components in PCA')
plt.xlabel('Number of Components')
plt.ylabel('Accuracy and variance')
plt.grid(True)

plt.show()

for component, accuracy, var in zip(n_components_values, accuracy_values, variance):
    print(f"For component value {component}, the accuracy is {accuracy} and variance is {var}")